server:
  port: 8084
spring:
  application:
    name: searchservice
  cloud:
    nacos:
      server-addr: localhost:8848
  rabbitmq:
    password: 123321
    username: itcast
    virtual-host: /
    host: 192.168.211.132
    port: 5672
  datasource:
    url: jdbc:mysql://localhost:3306/hmall?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
#  type-aliases-package: com.hmall.search.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
